---
version: 0.2
phases:
  install:
    commands:
      - wget https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tgz
      - tar -xvf Python-2.7.15.tgz
      - mv Python-2.7.15 python
  build:
    commands:
      - mvn install
artifacts:
  files:
    - target/*.war
  name: MyWebApp.war
